package com.framework.reporting;

import com.framework.config.ConfigKeys;
import com.framework.config.ConfigReader;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.io.InputStream;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Properties;

/**
 * Populates the Allure "Environment", "Executors" and "Categories" widgets so every report states exactly
 * where, how and by which CI run it was produced. Secrets are never written.
 */
public final class AllureEnvironmentWriter {

    private static final Logger LOG = LoggerFactory.getLogger(AllureEnvironmentWriter.class);
    private static final String RESULTS_DIR_PROPERTY = "allure.results.directory";
    private static final String DEFAULT_RESULTS_DIR = "allure-results";
    private static final String CATEGORIES_RESOURCE = "allure/categories.json";

    private AllureEnvironmentWriter() {
    }

    /**
     * Writes environment.properties, categories.json and (on GitHub Actions) executor.json.
     */
    public static void write() {
        Path resultsDir = resultsDirectory();
        try {
            Files.createDirectories(resultsDir);
            writeEnvironment(resultsDir);
            copyCategories(resultsDir);
            writeExecutor(resultsDir);
        } catch (IOException e) {
            LOG.warn("Could not write Allure environment metadata: {}", e.getMessage());
        }
    }

    private static void writeEnvironment(Path resultsDir) throws IOException {
        Map<String, String> values = new LinkedHashMap<>();
        values.put("Environment", ConfigReader.getEnvironment());
        values.put("Base URL", ConfigReader.get(ConfigKeys.APP_BASE_URL, "n/a"));
        values.put("Browser", ConfigReader.get(ConfigKeys.BROWSER, "n/a"));
        values.put("Headless", ConfigReader.get(ConfigKeys.HEADLESS, "false"));
        values.put("Selenium Grid", ConfigReader.get(ConfigKeys.GRID_URL, "local"));
        values.put("Parallel threads", ConfigReader.get(ConfigKeys.PARALLEL_THREADS, "1"));
        values.put("Retry max count", ConfigReader.get(ConfigKeys.RETRY_MAX_COUNT, "0"));
        values.put("API auth mode", ConfigReader.get(ConfigKeys.API_AUTH_MODE, "n/a"));
        values.put("Video mode", ConfigReader.get(ConfigKeys.VIDEO_MODE, "off"));
        values.put("Tag expression", System.getProperty("cucumber.filter.tags", "(runner default)"));
        values.put("Java", System.getProperty("java.version"));
        values.put("OS", System.getProperty("os.name"));

        Properties properties = new Properties();
        properties.putAll(values);
        try (Writer writer = Files.newBufferedWriter(resultsDir.resolve("environment.properties"),
                StandardCharsets.UTF_8)) {
            properties.store(writer, "Generated by AllureEnvironmentWriter");
        }
    }

    private static void copyCategories(Path resultsDir) throws IOException {
        try (InputStream stream = AllureEnvironmentWriter.class.getClassLoader()
                .getResourceAsStream(CATEGORIES_RESOURCE)) {
            if (stream != null) {
                Files.copy(stream, resultsDir.resolve("categories.json"), StandardCopyOption.REPLACE_EXISTING);
            }
        }
    }

    private static void writeExecutor(Path resultsDir) throws IOException {
        String runId = System.getenv("GITHUB_RUN_ID");
        if (runId == null) {
            return;
        }
        String runUrl = System.getenv("GITHUB_SERVER_URL") + "/" + System.getenv("GITHUB_REPOSITORY")
                + "/actions/runs/" + runId;
        String json = "{\"name\":\"GitHub Actions\",\"type\":\"github\",\"buildName\":\"Run #"
                + System.getenv("GITHUB_RUN_NUMBER") + "\",\"buildUrl\":\"" + runUrl + "\",\"reportName\":"
                + "\"OrangeHRM Employee Lifecycle\"}";
        Files.writeString(resultsDir.resolve("executor.json"), json, StandardCharsets.UTF_8);
    }

    private static Path resultsDirectory() {
        String configured = System.getProperty(RESULTS_DIR_PROPERTY);
        if (configured == null) {
            try (InputStream stream = AllureEnvironmentWriter.class.getClassLoader()
                    .getResourceAsStream("allure.properties")) {
                if (stream != null) {
                    Properties properties = new Properties();
                    properties.load(stream);
                    configured = properties.getProperty(RESULTS_DIR_PROPERTY);
                }
            } catch (IOException e) {
                LOG.debug("allure.properties could not be read: {}", e.getMessage());
            }
        }
        return Paths.get(configured == null ? DEFAULT_RESULTS_DIR : configured);
    }
}
